# Generated by Django 3.1.7 on 2021-03-19 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('NavigationApp', '0002_auto_20210320_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='NavigationApp.vehicle'),
        ),
    ]
