# Generated by Django 3.1.7 on 2021-03-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NavigationApp', '0003_auto_20210320_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
